# Generated by Django 2.0.2 on 2018-09-10 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consignee', models.CharField(max_length=50)),
                ('detailAddress', models.CharField(max_length=200)),
                ('postalcode', models.CharField(max_length=10)),
                ('telephone', models.CharField(max_length=12, null=True)),
                ('mobilephone', models.CharField(max_length=15, null=True)),
                ('userid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='login.User')),
            ],
            options={
                'db_table': 'd_address',
            },
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('amount', models.IntegerField()),
                ('subtotal', models.FloatField()),
            ],
            options={
                'db_table': 'd_orderitems',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderNumber', models.CharField(max_length=30)),
                ('dateInProduct', models.DateTimeField()),
                ('status', models.CharField(max_length=10)),
                ('freight', models.FloatField()),
                ('expenditure', models.FloatField(verbose_name=0)),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='indent.Address')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='login.User')),
            ],
            options={
                'db_table': 'd_orders',
            },
        ),
        migrations.AddField(
            model_name='orderitems',
            name='orderid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='indent.Orders'),
        ),
    ]
