# Generated by Django 2.0.2 on 2018-09-03 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales', models.IntegerField()),
                ('price', models.FloatField()),
                ('dangdang_price', models.FloatField()),
                ('score', models.FloatField(null=True)),
                ('issue', models.DateTimeField()),
                ('recommand', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'd_addproduct',
            },
        ),
        migrations.CreateModel(
            name='Menus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('parent', models.IntegerField()),
            ],
            options={
                'db_table': 'd_menus',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100, null=True)),
                ('face', models.ImageField(upload_to='media')),
                ('publishing_house', models.CharField(max_length=100)),
                ('edition', models.SmallIntegerField()),
                ('publishing_time', models.DateTimeField()),
                ('print_time', models.SmallIntegerField()),
                ('isbn', models.CharField(max_length=50)),
                ('word', models.IntegerField()),
                ('number_of_page', models.IntegerField(db_column='page')),
                ('format_of_book', models.CharField(db_column='format', max_length=30)),
                ('paper_size', models.CharField(max_length=10)),
                ('packaging', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=10)),
                ('menus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='index.Menus')),
            ],
            options={
                'db_table': 'd_product',
            },
        ),
        migrations.AddField(
            model_name='addproduct',
            name='product_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='index.Product'),
        ),
    ]
